server:
  port: 8080
  tomcat:
    threads:
      max: 5
#  ssl:
#    key-store: /home/ashish/apps/video-stream-app/api-server.p12
#    key-store-password: apiserver
#    key-store-type: PKCS12

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/passogen_crm?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    open-in-view: true
  
  mail:
    mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: aic.pajinkya@gmail.com
    password: Ajinkya@2803
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false